
version: '3'
services:
  converter_base_img:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["echo", "Base image build done"]

  videowiki_converter_en:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    command: ["node", "worker.js", "en"]

  videowiki_converter_hi:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_en}
    
    command: ["node", "worker.js", "hi"]

  videowiki_converter_es:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_hi}
    
    command: ["node", "worker.js", "es"]

  videowiki_converter_ar:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_es}
    
    command: ["node", "worker.js", "ar"]

  videowiki_converter_ja:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_ar}
    
    command: ["node", "worker.js", "ja"]

  videowiki_converter_uk:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_ja}
    
    command: ["node", "worker.js", "uk"]

  videowiki_converter_fr:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_uk}
    
    command: ["node", "worker.js", "fr"]

  videowiki_converter_or:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_fr}
    
    command: ["node", "worker.js", "or"]

  videowiki_converter_te:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_or}
    
    command: ["node", "worker.js", "te"]

  videowiki_converter_gu:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_te}
    
    command: ["node", "worker.js", "gu"]

  videowiki_converter_bn:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_gu}
    
    command: ["node", "worker.js", "bn"]

  videowiki_converter_pa:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_bn}
    
    command: ["node", "worker.js", "pa"]

  videowiki_converter_sat:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_pa}
    
    command: ["node", "worker.js", "sat"]

  videowiki_converter_sv:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_sat}
    
    command: ["node", "worker.js", "sv"]

  videowiki_converter_it:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_sv}
    
    command: ["node", "worker.js", "it"]

  videowiki_converter_in:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_it}
    
    command: ["node", "worker.js", "in"]

  videowiki_converter_kn:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_in}
    
    command: ["node", "worker.js", "kn"]

  videowiki_converter_ml:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_kn}
    
    command: ["node", "worker.js", "ml"]

  videowiki_converter_ta:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_ml}
    
    command: ["node", "worker.js", "ta"]

  videowiki_converter_eu:
    extends:
        service: converter_base_img
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_ta}
    
    command: ["node", "worker.js", "eu"]

