
version: '3'
services:

  videowiki_converter_en:
    image: videowiki/export:latest
    restart: unless-stopped
    
    command: ["node", "worker.js", "en"]

  videowiki_converter_hi:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_en
    
    command: ["node", "worker.js", "hi"]

  videowiki_converter_es:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_hi
    
    command: ["node", "worker.js", "es"]

  videowiki_converter_ar:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_es
    
    command: ["node", "worker.js", "ar"]

  videowiki_converter_ja:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_ar
    
    command: ["node", "worker.js", "ja"]

  videowiki_converter_uk:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_ja
    
    command: ["node", "worker.js", "uk"]

  videowiki_converter_fr:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_uk
    
    command: ["node", "worker.js", "fr"]

  videowiki_converter_or:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_fr
    
    command: ["node", "worker.js", "or"]

  videowiki_converter_te:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_or
    
    command: ["node", "worker.js", "te"]

  videowiki_converter_gu:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_te
    
    command: ["node", "worker.js", "gu"]

  videowiki_converter_bn:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_gu
    
    command: ["node", "worker.js", "bn"]

  videowiki_converter_pa:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_bn
    
    command: ["node", "worker.js", "pa"]

  videowiki_converter_sat:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_pa
    
    command: ["node", "worker.js", "sat"]

  videowiki_converter_sv:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_sat
    
    command: ["node", "worker.js", "sv"]

  videowiki_converter_it:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_sv
    
    command: ["node", "worker.js", "it"]

  videowiki_converter_in:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_it
    
    command: ["node", "worker.js", "in"]

  videowiki_converter_kn:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_in
    
    command: ["node", "worker.js", "kn"]

  videowiki_converter_ml:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_kn
    
    command: ["node", "worker.js", "ml"]

  videowiki_converter_ta:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_ml
    
    command: ["node", "worker.js", "ta"]

  videowiki_converter_eu:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_ta
    
    command: ["node", "worker.js", "eu"]

  videowiki_converter_ha:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_eu
    
    command: ["node", "worker.js", "ha"]

  videowiki_converter_zh:
    image: videowiki/export:latest
    restart: unless-stopped
    
    depends_on:
        - videowiki_converter_ha
    
    command: ["node", "worker.js", "zh"]
