const fs = require('fs');
const path = require('path');
const utils = require('./utils');
const FONT_SIZE = 28;

function generateSubtitle(text, audio, callback) {
  // Change color and font size of the references numbers
  const subtitleText = text.replace(/\[([0-9]+)\]/g, `{\\fs18}{\\c&HFF2E00&}[$1]{\\c&HFFFFFF&}{\\fs${FONT_SIZE}}`);

  utils.getRemoteFileDuration(audio, (err, duration) => {

    if (err) {
      return callback(err);
    }

    const fileContent = 
`
[Script Info]
; Script generated by Videowiki Exporter
; http://www.videowiki.wmflabs.org/
Title: Videowiki Generated subtitle
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1280
PlayResY: 720

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, AngleBorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Sans,${FONT_SIZE},&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:${duration},Default,,0,0,0,,${subtitleText}
`;
    const subtitleName = parseInt(Date.now() + Math.random() * 100000) + '-sub.ass';
    
    fs.writeFile(path.join(__dirname, subtitleName), fileContent, (err) => {
      if (err) {
        console.log('Error writing subtitle file ', err);
        return callback(err);
      }
      return callback(null, subtitleName);
    })
  })
}

module.exports = {
  generateSubtitle,
}

// generateSubtitle('Retinal detachment should be considered if there were preceding flashes or floaters, or if there is a new visual field defect in one eye.[3][4] If treated early enough, retinal tear and detachment can have a good outcome.[3]', 'https://dnv8xrxt73v5u.cloudfront.net/549754ec-5e55-472f-8715-47120efc4567.mp3', (err, filepath) => {
//   console.log(err, filepath)
// })