version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=\${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=\${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"